import Link from "next/link";
import { ArrowLeft, Building2, FileCheck, Landmark, Languages, Stamp, Users } from "lucide-react";
import { services } from "@/lib/content";
import { getGovernmentEntities } from "@/lib/api";

export const metadata = { title: "رَنيم لخدمات رجال الأعمال في دبي", description: "تأسيس الشركات وخدمات المعاملات الحكومية والتأشيرات والتصديق والترجمة القانونية في دولة الإمارات.", alternates: { canonical: "/ar", languages: { en: "/", ar: "/ar" } } };
const names: Record<string,string> = { "business-setup-uae":"تأسيس الشركات في الإمارات", "business-setup-dubai":"تأسيس الشركات في دبي", "mainland-company-formation":"تأسيس شركة في البر الرئيسي", "free-zone-company-formation":"تأسيس شركة في المنطقة الحرة", "pro-services-dubai":"خدمات العلاقات العامة والمعاملات الحكومية", "trade-license-renewal-dubai":"تجديد الرخصة التجارية", "uae-visa-services":"خدمات التأشيرات والإقامة", "document-attestation-dubai":"تصديق المستندات", "legal-translation-dubai":"الترجمة القانونية" };
const icons = [Building2, Landmark, Users, Stamp, Languages, FileCheck];
export default async function ArabicHome() {
  const authorities = await getGovernmentEntities();
  return <>
    <section className="bg-ink py-20 text-white md:py-28"><div className="container"><p className="eyebrow">خدمات الأعمال · دبي · الإمارات</p><h1 className="display mt-5 max-w-4xl">تأسيس الشركات والمعاملات الحكومية بوضوح ومتابعة موثوقة.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-300">نساعد رواد الأعمال والشركات والأفراد في التأسيس والتراخيص والتأشيرات والتصديق والترجمة والخدمات الحكومية في دولة الإمارات.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/contact" className="rounded-full bg-white px-6 py-3.5 font-bold text-navy">اطلب استشارة مجانية</Link><Link href="/ar/services" className="rounded-full border border-white/40 px-6 py-3.5 font-bold">استكشف الخدمات</Link></div></div></section>
    <section className="bg-mist py-16 md:py-24"><div className="container"><p className="eyebrow">خدماتنا</p><h2 className="section-title mt-4">دعم عملي في كل مرحلة</h2><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{services.slice(0,6).map((service,i)=>{const Icon=icons[i];return <Link href={`/ar/services/${service.slug}`} key={service.slug} className="rounded-2xl border bg-white p-6 shadow-sm transition hover:-translate-y-1"><Icon className="text-gold"/><h3 className="mt-5 text-xl font-extrabold">{names[service.slug] || service.title}</h3><p className="mt-3 text-sm leading-7 text-slate-600">نراجع متطلبات حالتك ونوضح المستندات والخطوات قبل بدء المعاملة.</p><span className="mt-6 flex items-center gap-2 text-sm font-bold text-royal">التفاصيل <ArrowLeft size={16}/></span></Link>})}</div></div></section>
    {authorities.length > 0 && <section className="py-16"><div className="container text-center"><p className="eyebrow">الجهات وقنوات الخدمة</p><h2 className="section-title mt-4">جهات نتعامل مع إجراءاتها</h2><div className="mt-9 flex flex-wrap items-center justify-center gap-5">{authorities.map(a=><a href={a.website || "#"} key={a._id} className="flex h-28 w-44 items-center justify-center rounded-xl border p-4"><img src={a.imageData} alt={a.nameAr || a.name} className="max-h-16 max-w-full"/></a>)}</div><p className="mx-auto mt-7 max-w-3xl text-xs leading-6 text-slate-500">جميع العلامات التجارية مملوكة لأصحابها. عرضها يوضح الجهات المرتبطة بالإجراءات ولا يعني شراكة أو اعتماداً حكومياً.</p></div></section>}
  </>;
}
